

name: User Banking App Frontend CI ( image push to ECR Registry and artifacts push to S3 )

on:
  push:
    branches:
      - 'ft/*'
      - 'Comflict/Check'
      - 'development'
      - 'update/*'

  pull_request:
    types: [opened, reopened, synchronize, merge, closed]
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci #This command ensures that the exact versions specified in package-lock.json are installed

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-cache-${{ github.sha }}
          restore-keys: |
            npm-cache-${{ github.ref_name }}-
            npm-restore

      - name: Build the application
        run: npm run build

      - name: Scan build artifacts for vulnerabilities
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          name: 'dist'
          path: '.'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v5.0.0
        with:
          name: dist
          path: .

      - name: Download a Build Artifact
        uses: actions/download-artifact@v5.0.0
        with:
          name: dist
          path: .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Amazon ECR Login
        uses: aws-actions/amazon-ecr-login@v2.0.1

      - name: Build Docker image
        id: build-image
        env:
          ECR_REGISTRY: 730335566159.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: user-banking/frontend11
          IMAGE_TAG: ${{ github.sha }}
        run: |
          IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker build -t $IMAGE_URI .
          echo "image_uri=$IMAGE_URI" >> $GITHUB_OUTPUT
          

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ steps.build-image.outputs.image_uri }}
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Push Docker image to ECR
        run: docker push ${{ steps.build-image.outputs.image_uri }}

      - name: Deploy to S3
        run: |
          aws s3 sync dist s3://user-banking-app11/ --delete
